# Project: VendingMachine
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = vendMain.o
LINKOBJ  = vendMain.o
LIBS     = -L"D:/cppfile/Dev-Cpp/MinGW64/lib" -L"D:/cppfile/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/cppfile/Dev-Cpp/MinGW64/include" -I"D:/cppfile/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/cppfile/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/cppfile/Dev-Cpp/MinGW64/include" -I"D:/cppfile/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/cppfile/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/cppfile/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = VendBeta.exe
CXXFLAGS = $(CXXINCS) -std=c++11
CFLAGS   = $(INCS) -std=c++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

vendMain.o: vendMain.cpp
	$(CPP) -c vendMain.cpp -o vendMain.o $(CXXFLAGS)
